// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet");
const Monetizer = artifacts.require("Monetizer");

module.exports = async function(deployer) {
  await deployer.link(Witnet, [Monetizer]);
  await deployer.deploy(Monetizer);
};
